### ISSUE TITLE
[TownyMenu] TownyMenuは1.12.2を想定していないので削除する

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/SeichiAssist-ExternalLib#65]
「/tm」のResidentMenuを開こうとすると以下エラー。
```
[Sat, 2. Oct 2021 12:00:00 JST INFO] [TownyMenu] TownyMenu 1.1.12 encountered a NoSuchFieldError! Please check your error.log and report this issue with the information in that file.
[Sat, 2. Oct 2021 12:00:00 JST INFO] java.lang.NoSuchFieldError: PLAYER_HEAD
[Sat, 2. Oct 2021 12:00:00 JST INFO] at net.tolmikarc.townymenu.town.TownMenu$ResidentListMenu.convertToItemStack(TownMenu.java:384)
[Sat, 2. Oct 2021 12:00:00 JST INFO] at net.tolmikarc.townymenu.town.TownMenu$ResidentListMenu.convertToItemStack(TownMenu.java:372)
[Sat, 2. Oct 2021 12:00:00 JST INFO] at net.tolmikarc.TownyMenu.lib.fo.menu.MenuPagged.getItemAt(MenuPagged.java:336)
[Sat, 2. Oct 2021 12:00:00 JST INFO] at net.tolmikarc.TownyMenu.lib.fo.menu.Menu.displayTo(Menu.java:378)
[Sat, 2. Oct 2021 12:00:00 JST INFO] at net.tolmikarc.TownyMenu.lib.fo.menu.button.ButtonMenu.onClickedInMenu(ButtonMenu.java:148)
[Sat, 2. Oct 2021 12:00:00 JST INFO] at net.tolmikarc.TownyMenu.lib.fo.menu.Menu.onButtonClick(Menu.java:775)
[Sat, 2. Oct 2021 12:00:00 JST INFO] at net.tolmikarc.TownyMenu.lib.fo.menu.MenuListener.onMenuClick(MenuListener.java:75)
[Sat, 2. Oct 2021 12:00:00 JST INFO] at sun.reflect.GeneratedMethodAccessor391.invoke(Unknown Source)
[Sat, 2. Oct 2021 12:00:00 JST INFO] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[Sat, 2. Oct 2021 12:00:00 JST INFO] at java.lang.reflect.Method.invoke(Method.java:498)
[Sat, 2. Oct 2021 12:00:00 JST INFO] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[Sat, 2. Oct 2021 12:00:00 JST INFO] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[Sat, 2. Oct 2021 12:00:00 JST INFO] at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[Sat, 2. Oct 2021 12:00:00 JST INFO] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[Sat, 2. Oct 2021 12:00:00 JST INFO] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[Sat, 2. Oct 2021 12:00:00 JST INFO] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[Sat, 2. Oct 2021 12:00:00 JST INFO] at java.lang.Thread.run(Thread.java:748)
[Sat, 2. Oct 2021 12:00:00 JST INFO] [TownyMenu] !-----------------------------------------------------!
[Sat, 2. Oct 2021 12:00:00 JST INFO] [TownyMenu]  Error clicking in menu TownMenu{}
[Sat, 2. Oct 2021 12:00:00 JST INFO] [TownyMenu] !-----------------------------------------------------!
```

**Comment by KisaragiEffective** [comment]
https://github.com/bennycio/TownyMenu/blob/d302bb753890f26c1113bdf136628ec03acef9f4/TownyMenu/pom.xml#L47

を参照すると、このプラグインは1.12.2向けにインストールされることを想定されていないように考えることができる。

**Comment by Lucky3028** [comment]
see #9
